[project]
name = "interview-sopra"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pandas>=2.2.3",
    "yr-weather>=0.4.0",
]

[dependency-groups]
dev = [
    "black[d]>=25.1.0",
]
